import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  selfHostingSidebar: [{type: 'autogenerated', dirName: 'self-hosting'}],
  userGuideSidebar: [{type: 'autogenerated', dirName: 'user-guide'}],
  contributingSidebar: [{type: 'autogenerated', dirName: 'contributing'}],
};

export default sidebars;
